micronaut:
  application:
    name: pet-clinic-concierge
  config-client:
    enabled: true

consul:
  client:
    registration:
      enabled: true
    config:
      defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
