micronaut:
  application:
    name: pet-clinic
  server:
    port: -1

kafka:
  bootstrap:
    servers: localhost:9094

endpoints:
  all:
    enabled: true
    sensitive: false

datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


consul:
  client:
    registration:
      enabled: true
