micronaut:
  application:
    name: pet-clinic
  server:
    port: 32582
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  security:
    authentication: idtoken
    endpoints:
      login:
        enabled: true
    redirect:
      login-success: /secure/anonymous
    token:
      jwt:
        enabled: true
        signatures.jwks.keycloak:
          url: http://host.docker.internal:8888/auth/realms/master/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      grant-type: password
      client-id: pet-clinic
      client-secret: 7d888c03-56e2-4f6d-980f-900a4407168b
      authorization:
        url: http://host.docker.internal:8888/auth/realms/master/protocol/openid-connect/auth
      token:
        url: http://host.docker.internal:8888/auth/realms/master/protocol/openid-connect/token
        auth-method: client_secret_post

endpoints:
  metrics:
    enabled: false
  prometheus:
    enabled: false

kafka:
  bootstrap:
    servers: kafka:9092

datasources:
  default:
    url: "jdbc:postgresql://host.docker.internal:5432/postgres"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


consul:
  client:
    default-zone: "consul:8500"
    registration:
      enabled: true

tracing:
  zipkin:
    http:
      url: http://host.docker.internal:9411
    enabled: true
    sampler:
      probability: 1
