version: '3'

services:
  consul:
    image: bitnami/consul:latest
    ports:
      - '8500:8500'
  
  zookeeper:
    image: bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/pet-clinic-reviews
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  

  kafka:
    image: bitnami/kafka:2-debian-10
    ports:
      - 9094:9094
    volumes:
      - kafka_data:/pet-clinic-reviews
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka
  
  
  pet-owner:
    image: "pet-owner-0.1-image"
    ports:
        - "32581:32581"
    depends_on:
        - consul
  
  pet-clinic:
    image: "pet-clinic-0.1-image"
    ports:
        - "32582:32582"
    depends_on:
        - kafka
        - consul
  
  pet-clinic-reviews:
    image: "pet-clinic-reviews-0.1-image"
    ports:
        - "32583:32583"
    depends_on:
        - kafka
        - consul
  
  pet-clinic-concierge:
    image: "pet-clinic-concierge-0.1-image"
    ports:
        - "32584:32584"
    depends_on:
        - consul    

volumes:
  zookeeper_data:
  kafka_data:  