version: 0.2

phases:
  build:
    commands:
      - echo building the application
      - mvn install

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'